name: 'testdbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
analysis-paths: ['analyses']
test-paths: ['tests']

models:
  testdbt:
    staging:
      +materialized: view