version: 2

models:
  - name: stg_customers
    description: Active customers.
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null